version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo_db
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  mongo_db: {}